# Generated by Django 5.1.5 on 2025-02-04 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('member_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('management_level', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('pl_id', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('office', models.CharField(max_length=100)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_register.employee')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admin_search.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('project_name', models.CharField(max_length=100)),
                ('lead_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_manager', to='user_register.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_register.team'),
        ),
    ]
