# Generated by Django 5.1.4 on 2025-02-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_search', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_number', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('role', models.CharField(max_length=100)),
                ('management_level', models.CharField(max_length=100)),
                ('home_office', models.CharField(max_length=100)),
                ('team_id', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('pl_id', models.CharField(max_length=100)),
                ('manager_id', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
            ],
        ),
    ]
