# Generated by Django 5.1.5 on 2025-02-05 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_remove_team_description_remove_teammember_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_identifier',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='team.customuser'),
        ),
    ]
